apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-5cqt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-5cqt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-5cqt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-5cqt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-5cqt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rmiw-tenant/rhtap-demo-app/hacbs-test-project-5cqt@sha256:230bab47b27a47bc79b27bd1bb253454f60a439e438ef3f8660291f6d21cc41e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
